"""Generate the settings.yml SearXNG runs with, and the environment around it.

Split out of `searxng_manager.py` (see that module for the two backends this
feeds): everything here is about *what SearXNG is told*, not how it is
started: the managed settings.yml (secret key preserved across rewrites,
rate-limited/hostile engines removed, JSON API turned on), the environment
variables layered on top for a from-source run, and the one platform shim
SearXNG's own source needs on Windows (`pwd`, imported at module scope in
`searx/valkeydb.py` and unimportable there).
"""

from __future__ import annotations

import logging
import os
import secrets
from pathlib import Path

from memorymap.search import searxng_manager
from memorymap.search.searxng_manager import (
    COMMAND_TIMEOUT,
    SearxngError,
    _source_dir,
    base_url,
    host_port,
)

# `_run` is deliberately not imported by name above: the test suite
# monkeypatches it as `searxng_manager._run`, which only rebinds that
# attribute on the `searxng_manager` module object. `_write_pwd_shim` below
# calls it as `searxng_manager._run` so a patched or a real implementation is
# picked up exactly as it was when this was one file.

# use_default_settings keeps SearXNG's own defaults and layers ours on top, 
# the important bit being the json format, without which the API returns 403.
#
# Engine defaults: several engines that SearXNG ships are broken or hostile
# for a local/private install, and a broken engine is not a quiet failure, 
# module import and engine init happen at startup, so one bad engine fills
# the start window with tracebacks and can sink the whole start. They are
# *removed* here, not merely `disabled: true`, for two reasons this module
# learned the hard way:
#
#   - A disabled engine still gets imported. `bilibili` is disabled in
#     SearXNG's own defaults and still crashed every Windows start, because
#     it calls ZoneInfo("Asia/Shanghai") at module scope and Windows has no
#     IANA tzdata.
#   - An entry added under `engines:` merges *over* the default entry of the
#     same name, key by key. Upstream's `torch` engine is really the `xpath`
#     module in disguise (`name: torch, engine: xpath`), so an override that
#     said `engine: torch` sent SearXNG looking for a `torch.py` that does
#     not exist: FileNotFoundError, from our own settings file.
#
# `use_default_settings.engines.remove` has neither problem: a removed engine
# is never imported at all, and the loader treats it as a plain name filter,
# so a name upstream has meanwhile dropped is a no-op rather than a crash.
# What is removed, and why:
#
#   - google / bing: aggressively rate-limit automated requests from home IPs
#     and answer HTTP 403 (suspended_time=180), which makes every search hang
#     while SearXNG waits them out.
#   - wikidata: performs an outbound HTTP request during engine *init* and
#     fails it with an ERROR log on every startup of a home install.
#   - brave: requires an API key; returns 403 without one.
#   - ahmia / torch: Tor onion-network engines: useless without a Tor proxy,
#     and both have broken startup on a plain install.
#   - bilibili: the module-scope tzdata crash above.
#
# duckduckgo, the most permissive engine for private instances, is enabled
# in SearXNG's own defaults and is the working default here. The user can
# edit settings.yml, but MemoryMap rewrites the managed sections on each
# start, preserving secret_key (pass rewrite=False to ensure_settings to
# keep a hand-edited file as-is).
SETTINGS_TEMPLATE = """# Generated by MemoryMap.  Edit freely; MemoryMap refreshes managed sections on each start.
use_default_settings:
  engines:
    remove:
      - google
      - bing
      - wikidata
      - brave
      # Removing an engine must take every engine that shares its network:
      # these three declare `network: brave`, and SearXNG's network init
      # does NETWORKS[name] = NETWORKS['brave'], KeyError once brave is
      # gone, and the whole start dies on it.
      - brave.images
      - brave.videos
      - brave.news
      - ahmia
      - torch
      - bilibili{extra_removes}
server:
  secret_key: "{secret}"
  # Safe ONLY because the instance is bound to loopback, the source path sets
  # SEARXNG_BIND_ADDRESS=127.0.0.1 and the docker path publishes
  # 127.0.0.1:PORT. The limiter is SearXNG's bot/abuse protection; with it off
  # and the port reachable from the network, anyone on that network could run
  # searches through this instance. If the bind address is ever widened, this
  # has to be turned on in the same change.
  limiter: false
  # Result images are fetched by SearXNG and passed on, rather than by the
  # browser going to the result's own domain. Without it, merely *rendering*
  # a result page tells every pictured site that someone searched and got
  # them back: before anything is clicked.
  image_proxy: true
search:
  safe_search: 0
  formats:
    - html
    - json
  # Off explicitly, not just by default. Autocomplete sends a fragment of
  # every query to a third-party suggestion endpoint as it is typed, the one
  # thing in a search UI that leaks even when no search is ever run. SearXNG
  # already defaults it off; pinning it here means a changed upstream default
  # or a hand-edited file cannot quietly turn it back on, and this file is
  # rewritten on every start anyway so it costs nothing to state.
  # (MemoryMap itself only ever calls the JSON API, so this protects the
  # SearXNG web UI that is also reachable on the same port.)
  autocomplete: ""
outgoing:
  # Short timeouts prevent a single blocked engine from stalling all results.
  request_timeout: 3.0
  max_request_timeout: 6.0
engines:
  # One general engine is not enough: DuckDuckGo rate-limits by IP, and a
  # home instance that leans on it alone goes dark the moment it throttles.
  # Qwant and Mojeek run their own indexes and tolerate private instances.
  # Deliberately no `engine:` key: these merge onto the default entries by
  # name and only flip `disabled`, so they can never point an entry at a
  # module that is not there (which is how the torch override broke starts).
  - name: qwant
    disabled: false
  - name: mojeek
    disabled: false
plugins:
  # Off deliberately. This plugin downloads a rules file from
  # rules1.clearurls.xyz *during startup*, and a failure there is not caught:
  # the fetch raises, `searx.plugins.initialize` propagates it, and the
  # process exits before it ever binds the port. Any machine that is offline,
  # behind a proxy, or merely slow gets "SearXNG started but never answered".
  # MemoryMap strips tracking parameters from result URLs itself
  # (`websearch.strip_tracking`), so nothing is lost by leaving it off.
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: false
"""


# SearXNG imports `pwd` at module scope in `searx/valkeydb.py`, and `pwd` is a
# POSIX-only stdlib module. So `import searx.webapp`, the first thing a start
# does: dies on Windows with:
#
#     File "…\\searx\\valkeydb.py", line 22, in <module>
#         import pwd
#     ModuleNotFoundError: No module named 'pwd'
#
# reported with a photo. It is the *only* POSIX-only import in the whole
# package, and the only thing it is used for is one line of an error message
# ("[user (uid)] can't connect valkey DB") in a branch that is unreachable
# unless a Valkey/Redis URL is configured, which MemoryMap never does.
#
# So a stand-in module is written into the virtualenv where the platform
# hasn't got one. Not a patch to SearXNG's own source: a patch has to match
# text upstream is free to change and would need re-applying after every
# update. This is a compatibility shim for a stdlib module that isn't there,
# it lives only inside SearXNG's own venv, and it says what it is.
_PWD_SHIM = '''"""A stand-in for the POSIX-only `pwd` module, written by MemoryMap.

SearXNG imports `pwd` at module scope in `searx/valkeydb.py`, which makes it
unimportable on Windows. It uses it in exactly one place, naming the current
user in an error message when a Valkey DB connection fails, and MemoryMap
configures no Valkey DB, so that line never runs.

If it ever does run, these values are honest about being placeholders rather
than pretending to be a real passwd entry.
"""

import getpass
from collections import namedtuple

struct_passwd = namedtuple(
    "struct_passwd",
    "pw_name pw_passwd pw_uid pw_gid pw_gecos pw_dir pw_shell",
)


def _entry(uid=0):
    try:
        name = getpass.getuser() or "unknown"
    except Exception:  # noqa: BLE001 - a name for a log line is never worth raising
        name = "unknown"
    return struct_passwd(name, "x", uid, uid, name, "", "")


def getpwuid(uid=0):
    return _entry(uid)


def getpwnam(name):
    return _entry()


def getpwall():
    return [_entry()]
'''


def _searxng_env(data_dir: Path) -> dict:
    """The environment SearXNG runs in, the generated settings included.

    Used by the start *and* by the install's final check, because verifying
    against SearXNG's own defaults is verifying something nobody will ever
    run: it refuses to start on its placeholder `secret_key`, so the check
    failed on a file the app replaces anyway.
    """
    return {
        **os.environ,
        "SEARXNG_SETTINGS_PATH": str(ensure_settings(data_dir)),
        "SEARXNG_PORT": str(host_port()),
        "SEARXNG_BIND_ADDRESS": "127.0.0.1",
        "SEARXNG_BASE_URL": f"{base_url()}/",
        # The child's stdout goes to a file, which Python block-buffers: a
        # start that died mid-way could take its last lines with it, and
        # those lines are the whole point of keeping the log.
        "PYTHONUNBUFFERED": "1",
    }


def _write_pwd_shim(python: str) -> bool:
    """Give the virtualenv a `pwd` module if its platform hasn't got one.

    Asks the interpreter rather than checking `os.name`: whether *that* Python
    can import it is the thing that actually breaks, and the answer stays
    right if this ever runs somewhere unexpected.
    """
    if searxng_manager._run([python, "-c", "import pwd"], timeout=COMMAND_TIMEOUT).returncode == 0:
        return False
    where = searxng_manager._run(
        [python, "-c", "import sysconfig; print(sysconfig.get_paths()['purelib'])"],
        timeout=COMMAND_TIMEOUT,
    )
    target = (where.stdout or "").strip()
    if not target:
        raise SearxngError(
            "Couldn't find where to add a compatibility module in SearXNG's "
            "virtualenv."
        )
    Path(target, "pwd.py").write_text(_PWD_SHIM, encoding="utf-8")
    logging.getLogger("memorymap.searxng").info(
        "Wrote a `pwd` compatibility module into %s, SearXNG imports it at "
        "module scope and this platform has no such module.",
        target,
    )
    return True


def settings_path(data_dir: Path) -> Path:
    """Where the generated settings live (mounted into the container)."""
    return Path(data_dir) / "searxng" / "settings.yml"


def _existing_secret_key(path: Path) -> str | None:
    """Pull secret_key out of an existing settings file, if there is one."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("secret_key:"):
            value = stripped.split(":", 1)[1].strip().strip('"').strip("'")
            return value or None
    return None


# The names SETTINGS_TEMPLATE removes, kept in one place so the network-ref
# scan below can reason about them without re-parsing our own template.
REMOVED_ENGINES = (
    "google",
    "bing",
    "wikidata",
    "brave",
    "brave.images",
    "brave.videos",
    "brave.news",
    "ahmia",
    "torch",
    "bilibili",
)


def _engines_sharing_removed_networks(defaults_text: str, removed: set[str]) -> list[str]:
    """Engines in SearXNG's own settings.yml whose `network:` names one of
    ours. A light line scan rather than a YAML parse: MemoryMap doesn't
    depend on a YAML library, and the file is machine-formatted."""
    found: list[str] = []
    name = None
    in_engines = False
    for line in defaults_text.splitlines():
        if line.startswith("engines:"):
            in_engines = True
            continue
        if in_engines and line and not line[0].isspace():
            break  # left the engines block
        if not in_engines:
            continue
        stripped = line.strip()
        if stripped.startswith("- name:"):
            name = stripped.split(":", 1)[1].strip().strip("'\"")
        elif stripped.startswith("network:") and name and name not in removed:
            network = stripped.split(":", 1)[1].strip().strip("'\"")
            if network in removed:
                found.append(name)
    return found


def _extra_removes(data_dir: Path) -> list[str]:
    """Engines the installed checkout forces us to remove along with ours.

    The brave lesson, generalised: SearXNG's network init runs
    `NETWORKS[name] = NETWORKS[network]` for every engine that borrows
    another's network, and a borrowed name we removed is a KeyError that
    kills the whole start. Upstream is free to add such engines at any
    time, so the list is read from the checkout's own settings.yml at
    write time rather than predicted here. Empty when there is no checkout
    to read (Docker ships defaults the static list already covers).
    """
    defaults = _source_dir(data_dir) / "searx" / "settings.yml"
    try:
        text = defaults.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    removed = set(REMOVED_ENGINES)
    extra: list[str] = []
    while True:  # a borrower can itself be borrowed from; chase to a fixpoint
        found = _engines_sharing_removed_networks(text, removed)
        if not found:
            return extra
        extra.extend(found)
        removed.update(found)


def _restrict(path: Path, mode: int) -> None:
    """Keep a path to this user. Best effort, deliberately.

    settings.yml holds the instance's `secret_key` in clear text, because
    SearXNG reads it from there, encrypting it would only move the problem
    to wherever that key lived. What we *can* do is make sure nothing else
    on the machine can read it, which is the actual exposure.

    Never fatal: Windows ignores POSIX mode bits, and a FAT/exFAT data
    directory has nowhere to store them. Refusing to run SearXNG because a
    filesystem cannot express permissions would trade a working feature for
    no security gain at all.
    """
    try:
        path.chmod(mode)
    except OSError as exc:
        logging.debug(
            "Could not apply mode %o to %s (non-fatal): %s",
            mode,
            path,
            exc,
        )


def ensure_settings(data_dir: Path, rewrite: bool = True) -> Path:
    """Write the managed settings file, refreshing it by default so fixes
    to engine defaults (rate-limited engines, timeouts, plugins) reach
    installs that were set up before those fixes existed. The secret_key
    is preserved across rewrites so sessions aren't invalidated. Pass
    rewrite=False to leave a hand-edited file alone."""
    path = settings_path(data_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    _restrict(path.parent, 0o700)
    secret = _existing_secret_key(path) or secrets.token_hex(24)
    if rewrite or not path.exists():
        extra = "".join(f"\n      - {name}" for name in _extra_removes(data_dir))
        # CodeQL flags this as clear-text storage of a secret, and it is, 
        # unavoidably. SearXNG reads `server.secret_key` out of its own
        # settings.yml as plain text and will not start without it, so
        # encrypting it here would only move the exposure to wherever the
        # key that decrypts it had to live. The mitigation that does apply
        # is access control (_restrict, above and below: 0600 file, 0700
        # directory), plus the fact that this key signs one local instance's
        # sessions and is regenerated by deleting the file.
        content = SETTINGS_TEMPLATE.format(secret=secret, extra_removes=extra)
        path.write_text(content, encoding="utf-8")  # codeql[py/clear-text-storage-sensitive-data]
    # Every time, not only on write: a file created before this existed is
    # exactly the one still sitting there world-readable.
    _restrict(path, 0o600)
    return path
