const { boot } = require('./lib.js');
(async () => {
  const { browser, page } = await boot();
  await page.waitForTimeout(1200);
  await page.evaluate(() => switchTab('chat'));
  await page.waitForTimeout(2200);
  const sh = () => page.evaluate(() => { const d = document.querySelector('.chat-dock'); return { s: getComputedStyle(d).boxShadow, b: getComputedStyle(d).borderColor, held: d.classList.contains('ring-held'), fw: d.matches(':focus-within') }; });
  console.log('arrive  ', JSON.stringify(await sh()));
  await page.keyboard.type('h');
  await page.waitForTimeout(250);
  console.log('typed   ', JSON.stringify(await sh()));
  await page.evaluate(() => switchTab('notes'));
  await page.waitForTimeout(700);
  await page.evaluate(() => switchTab('chat'));
  await page.waitForTimeout(1500);
  console.log('re-enter', JSON.stringify(await sh()));
  await page.click('#chat-input');
  await page.waitForTimeout(250);
  console.log('clicked ', JSON.stringify(await sh()));
  await page.evaluate(() => switchTab('notes'));
  await page.waitForTimeout(600);
  await page.evaluate(() => switchTab('chat'));
  await page.waitForTimeout(1500);
  console.log('re-enter', JSON.stringify(await sh()));
  await page.click('body', { position: { x: 5, y: 400 } }).catch(()=>{});
  await page.waitForTimeout(300);
  await page.click('#chat-input');
  await page.waitForTimeout(300);
  console.log('out+in  ', JSON.stringify(await sh()));
  await browser.close();
})();
